package com.app.citas.Estados;

public enum EstadoBot {

    MENU,
    YA_TIENE_CITA,
    SELECCION_SUCURSAL,
    SELECCION_EMPLEADO,
    SELECCION_SERVICIO,
    SELECCION_FECHA,
    CREAR_CITA,
    SELECCION_HORA_SUGERIDA
}
